/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attachment {
  'data' : Uint8Array,
  'mimeType' : string,
  'filename' : string,
}
export type BackendError = { 'participantIdEmpty' : null } |
  { 'displayNameEmpty' : null };
export type CreateSessionResult = { 'ok' : string } |
  { 'err' : BackendError };
export interface Message {
  'displayName' : string,
  'sender' : string,
  'timestamp' : bigint,
  'attachment' : [] | [Attachment],
  'textContent' : [] | [string],
}
export interface Participant {
  'id' : string,
  'displayName' : string,
  'lastTypingTimestamp' : [] | [bigint],
  'isTyping' : boolean,
}
export interface SessionData {
  'participants' : Array<Participant>,
  'messages' : Array<Message>,
}
export interface _SERVICE {
  'createSession' : ActorMethod<[string, string], CreateSessionResult>,
  'getSessionData' : ActorMethod<[string], SessionData>,
  'joinSession' : ActorMethod<[string, string, string], undefined>,
  'sendMessage' : ActorMethod<
    [string, string, [] | [string], string, [] | [Attachment]],
    undefined
  >,
  'updateTypingIndicator' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];