/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BackendError = IDL.Variant({
  'participantIdEmpty' : IDL.Null,
  'displayNameEmpty' : IDL.Null,
});
export const CreateSessionResult = IDL.Variant({
  'ok' : IDL.Text,
  'err' : BackendError,
});
export const Participant = IDL.Record({
  'id' : IDL.Text,
  'displayName' : IDL.Text,
  'lastTypingTimestamp' : IDL.Opt(IDL.Int),
  'isTyping' : IDL.Bool,
});
export const Attachment = IDL.Record({
  'data' : IDL.Vec(IDL.Nat8),
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
});
export const Message = IDL.Record({
  'displayName' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : IDL.Int,
  'attachment' : IDL.Opt(Attachment),
  'textContent' : IDL.Opt(IDL.Text),
});
export const SessionData = IDL.Record({
  'participants' : IDL.Vec(Participant),
  'messages' : IDL.Vec(Message),
});

export const idlService = IDL.Service({
  'createSession' : IDL.Func([IDL.Text, IDL.Text], [CreateSessionResult], []),
  'getSessionData' : IDL.Func([IDL.Text], [SessionData], ['query']),
  'joinSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'sendMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Opt(Attachment)],
      [],
      ['oneway'],
    ),
  'updateTypingIndicator' : IDL.Func([IDL.Text, IDL.Text], [], ['oneway']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BackendError = IDL.Variant({
    'participantIdEmpty' : IDL.Null,
    'displayNameEmpty' : IDL.Null,
  });
  const CreateSessionResult = IDL.Variant({
    'ok' : IDL.Text,
    'err' : BackendError,
  });
  const Participant = IDL.Record({
    'id' : IDL.Text,
    'displayName' : IDL.Text,
    'lastTypingTimestamp' : IDL.Opt(IDL.Int),
    'isTyping' : IDL.Bool,
  });
  const Attachment = IDL.Record({
    'data' : IDL.Vec(IDL.Nat8),
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
  });
  const Message = IDL.Record({
    'displayName' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : IDL.Int,
    'attachment' : IDL.Opt(Attachment),
    'textContent' : IDL.Opt(IDL.Text),
  });
  const SessionData = IDL.Record({
    'participants' : IDL.Vec(Participant),
    'messages' : IDL.Vec(Message),
  });
  
  return IDL.Service({
    'createSession' : IDL.Func([IDL.Text, IDL.Text], [CreateSessionResult], []),
    'getSessionData' : IDL.Func([IDL.Text], [SessionData], ['query']),
    'joinSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'sendMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Opt(Attachment)],
        [],
        ['oneway'],
      ),
    'updateTypingIndicator' : IDL.Func([IDL.Text, IDL.Text], [], ['oneway']),
  });
};

export const init = ({ IDL }) => { return []; };